//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDbfReaderEx.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NDbfReaderEx.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///// template source is CreatePocoClassDynamicTemplate.cs
        ///// If any line contains /*DROP_LINE*/ text, it will not copy to target
        ///
        ///namespace NDbfReaderEx.Template
        ///{
        ///  using NDbfReaderEx;
        ///
        ///  public class CreatePocoClassDynamicTemplate
        ///  { 
        ///    public const CreatePocoClass.PocoType type = CreatePocoClass.PocoType.Dynamic;
        ///    public static bool partiallyFilledEnable { get; private set; }
        ///
        ///    // enum definitio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreatePocoClassDynamicTemplate {
            get {
                return ResourceManager.GetString("CreatePocoClassDynamicTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///// template source is CreatePocoClassHardWiredTemplate.cs
        ///// If any line contains /*DROP_LINE*/ text, it will not copy to target
        ///
        ///namespace NDbfReaderEx.Template
        ///{
        ///  public class CreatePocoClassHardWiredTemplate
        ///  { 
        ///    public const CreatePocoClass.PocoType type = CreatePocoClass.PocoType.HardWired;
        ///
        ///    // enum definition for fields of DBF table
        ///    //! &apos;/*FIELDNAMES*/&apos; changed to properties definition, d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreatePocoClassHardWiredTemplate {
            get {
                return ResourceManager.GetString("CreatePocoClassHardWiredTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///// template source is CreatePocoClassSoftWiredTemplate.cs
        ///// If any line contains /*DROP_LINE*/ text, it will not copy to target
        ///
        ///namespace NDbfReaderEx.Template
        ///{
        ///  using NDbfReaderEx;
        ///
        ///  public class CreatePocoClassSoftWiredTemplate
        ///  { 
        ///    public const  CreatePocoClass.PocoType type = CreatePocoClass.PocoType.SoftWired;
        ///    public static bool partiallyFilledEnable { get; private set; }
        ///
        ///    // enum de [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreatePocoClassSoftWiredTemplate {
            get {
                return ResourceManager.GetString("CreatePocoClassSoftWiredTemplate", resourceCulture);
            }
        }
    }
}
